name: lemon
description: "LemonğŸ‹â€ - offline music player"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  get_it: ^8.0.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  crypto: ^3.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  audio_video_progress_bar: ^2.0.3
  meta: ^1.15.0
  rxdart: ^0.28.0
  file_picker: ^8.1.3
  path: ^1.9.0
  audio_service: ^0.18.15
  share_plus: ^10.1.2
  flutter_launcher_icons: ^0.14.3
  audiotags: ^1.4.3
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - "assets/lang/appInfo/zh.json"
    - "assets/lang/appInfo/en.json"
    - "assets/default_cover.jpeg"
